import "./globals.css";
import localFont from 'next/font/local'
import { ThemeProvider } from "./context/ProvidersDarkTheme";

const myFont = localFont({
  src: 'MN Kai Waan.ttf',
})
export const metadata = {
  title: "My Expense Kn",
  description: "Generated by Kn",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={myFont.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
